app.frontend.url=${APP_FRONTEND}
app.backend.url=${APP_BACKEND}

# kakao
kakao.rest-api-key=${KAKAO_API_KEY}

# redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.username=${REDIS_USERNAME}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.ssl.enabled=true

# jwt
jwt.expiration=3600000
jwt.refresh-expiration=604800000
jwt.secret=${JWT_SECRET}

# local database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.password=${DB_PASSWORD}
spring.datasource.hikari.maximum-pool-size=10

# logging
logging.level.root=info
logging.level.org.hibernate.SQL=warn
logging.level.org.hibernate.type.descriptor.sql=warn
logging.level.org.springframework.cloud.openfeign=warn
logging.level.org.springframework.security=warn
logging.level.org.springframework.web.client.RestTemplate=warn
logging.level.org.springframework.security.oauth2.client.authentication.OAuth2LoginAuthenticationProvider=warn
logging.level.org.springframework.security.oauth2.core.http.converter=warn
spring.cloud.openfeign.client.config.default.logger-level=basic

# jpa
spring.jpa.open-in-view=false
spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.cloud.gcp.secretmanager.enabled=false

# public data api key
external.api.url=${EXTERNAL_API_URL}
external.api.key=${EXTERNAL_API_KEY}

spring.jmx.enabled=false
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false
spring.devtools.restart.enabled=false

# email
spring.mail.host=smtp.gmail.com
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# naver
naver.ocr.invoke-url=${NAVER_OCR_URL}
naver.ocr.secret-key=${NAVER_OCR_KEY}

# oauth
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_OAUTH_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_OAUTH_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri=${APP_BACKEND}/login/oauth2/code/google
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://openidconnect.googleapis.com/v1/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub

# gemini
gemini.api.key=${GEMINI_API_KEY}

# aws
cloud.aws.s3.bucket=${AWS_BUCKET}
cloud.aws.region.static=ap-northeast-2
cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID}
cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY}