appender=com.p6spy.engine.spy.appender.StdoutLogger
logMessageFormat=com.p6spy.engine.spy.appender.CustomLineFormat
customLogMessageFormat=\n[P6SPY] %(executionTime)ms | %(sql)
driverlist=org.postgresql.Driver
